### ISSUE TITLE
[New feature] Allow MQTT broker in Domoticz standard

### ISSUE THREAD

**Issue by sq4bja** [dtlzp/Domoticz-Dingtian-Relay-Plugin#3]
A great functionality would be adding MQTT support in the Domoticz standard. Then direct UDP connections between Domoticz and Dingtian module can be replaced with the MQTT protocol.

**Comment by dtlzp** [comment]
Domoticz not integrated MQTT Broker,so need install third party MQTT Broker(mosquitto,ActiveMQ,EMQ X....),maybe the third party MQTT Broker will add some complexity
MQTT is good,we will consider adding it,but it will not be soon


 
From: sq4bja
Date: 2021-05-01 19:31
To: dtlzp/Domoticz-Dingtian-Relay-Plugin
CC: Subscribed
Subject: [dtlzp/Domoticz-Dingtian-Relay-Plugin] [New feature] Allow MQTT broker in Domoticz standard (#3)
A great functionality would be adding MQTT support in the Domoticz standard. Then direct UDP connections between Domoticz and Dingtian module can be replaced with the MQTT protocol.
