### ISSUE TITLE
Not able to turn off relay

### ISSUE THREAD

**Issue by FirelightLokeren** [dtlzp/Domoticz-Dingtian-Relay-Plugin#5]
Hi, I installed the plugin and I'm able to turn on the relay but not off.
when I turn on the relay, I hear the relay clicking but in domoticz the status is not changed.

When I contol the relay with the corresponding input I hear the relay, but no status change in Domoticz

Domoticz version Version: 2023.1
Relay version  V3.6J  V3.1.2178A

**Comment by dtlzp** [comment]
Hi,

when Domoticz control relay ON/OFF is ok, but can't get relay and input status.
it means computer firewall refused the UDP data from relay board,
so you need close computer firewall allow UDP data from relay board.



 
From: FirelightLokeren
Date: 2023-04-27 04:46
To: dtlzp/Domoticz-Dingtian-Relay-Plugin
CC: Subscribed
Subject: [dtlzp/Domoticz-Dingtian-Relay-Plugin] Not able to turn off relay (Issue #5)
Hi, I installed the plugin and I'm able to turn on the relay but not off.
when I turn on the relay, I hear the relay clicking but in domoticz the status is not changed.
When I contol the relay with the corresponding input I hear the relay, but no status change in Domoticz
Domoticz version Version: 2023.1
Relay version V3.6J V3.1.2178A

**Comment by dtlzp** [comment]
<user_manual_en.pdf> chapter "Appendix II How to use Domoticz" -> "step 2: config Dingtian Relay board"
shows how to config relay board for Domoticz

UDP1 and UDP2 need config "Remote Address" to you computer(Domoticz) IP
UDP1 port must be 60000, protocol must be "Dingtian Binary"
UDP2 port must be 60001, protocol must be "Dingtian String"



 
From: FirelightLokeren
Date: 2023-04-27 04:46
To: dtlzp/Domoticz-Dingtian-Relay-Plugin
CC: Subscribed
Subject: [dtlzp/Domoticz-Dingtian-Relay-Plugin] Not able to turn off relay (Issue #5)
Hi, I installed the plugin and I'm able to turn on the relay but not off.
when I turn on the relay, I hear the relay clicking but in domoticz the status is not changed.
When I contol the relay with the corresponding input I hear the relay, but no status change in Domoticz
Domoticz version Version: 2023.1
Relay version V3.6J V3.1.2178A

**Comment by FirelightLokeren** [comment]
Hi,

Thx for the quick response. 
UDP remote address was set wrong. 
Now it is working as it should.

Kind Regards
Koen
